### ISSUE TITLE
What version are the derived Ecodes? (in the most recent download)

### ISSUE THREAD

**Issue by stormluvr** [ablack3/icdpicr#16]
I am using icdpic-R for calculating AIS and severity codes for our linked crash - hospital discharge data for 2019. All the codes are from ICD-10. I am attaching an Excel file that contains the input diagnosis codes and the non-empty output codes from one record that confused me. By the way, this specific discharge record has not linked with a crash record, and it has ICD-10 diagnosis codes that begin with "E." I ran the program with this command: severity <- cat_trauma(icd_codes, dx_pre = "DIAG", icd10 = "cm", i10_iss_method="roc_max_NIS").
I'm a little confused about the derived E-codes in the output from cat_trauma(). If I look them up in the ICD-10, they have meanings related to post-procedural hypoparathyroidism or endocrine / metabolic diseases, which are not external causes of injury and poisoning. When I look them up as ICD-9 E-codes, then I see causes related to water transport and fire, which are not indicated by the diagnosis codes. This, to me, implies that the Mechmaj1 text is not necessarily related to the diagnosis codes in a record. Is that right? It would be helpful to get ICD-10 injury codes, which all start with V thru Y.
[eg.xlsx](https://github.com/ablack3/icdpicr/files/6368222/eg.xlsx)

**Comment by ablack3** [comment]
I think your E codes are being interpreted as ICD-9 E codes which is a problem. We allow both ICD-9 and ICD-10 codes in a single dataset which causes a problem for codes that are in both ICD-9 and ICD-10. However there are no codes that are injury codes in both ICD-9 and ICD-10 so when we find a code that is in both we assume it is an injury code. In this case icdpicr is assuming that E8339 is "ICD 9 Diagnosis Code: E8339 - Fall on stairs or ladders in water transport injuring unspecified person" which has a mechanism annotation of "Transport, other".  The Mechmaj text should be related to the E codes.

icdpicr does identify ICD-10 external cause of injury codes. It should find the first four and add the correct annotations.

Here is an example with a couple V codes. 
``` r
library(icdpicr)


df <- data.frame(dx1 = "V30.3", dx2 = "V29.09", stringsAsFactors = F)
cat_trauma(df, "dx", icd10 = "cm", i10_iss_method = "roc_max_NIS")
#>     dx1 sev_1 issbr_1    dx2 sev_2 issbr_2 mxaisbr_General mxaisbr_HeadNeck
#> 1 V30.3    NA    <NA> V29.09    NA    <NA>               0                0
#>   mxaisbr_Face mxaisbr_Extremities mxaisbr_Chest mxaisbr_Abdomen maxais riss
#> 1            0                   0             0               0      0    0
#>   niss ecode_1         mechmaj1 mechmin1       intent1 ecode_2         mechmaj2
#> 1   NA    V303 Transport, other     <NA> Unintentional    V290 Transport, other
#>   mechmin2       intent2 ecode_3 mechmaj3 mechmin3 intent3 ecode_4 mechmaj4
#> 1     <NA> Unintentional    <NA>     <NA>     <NA>    <NA>    <NA>     <NA>
#>   mechmin4 intent4 mortality_prediction
#> 1     <NA>    <NA>           0.02048297
```

<sup>Created on 2021-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

One possible improvement we could make is to remove the ability to process mixed ICD9 and ICD10 codes which would remove all ambiguity. 

Thanks for using the package and providing feedback.

**Comment by stormluvr** [comment]
Thanks - that answers my question.
